services:
  postgres:
    image: postgres:16
    container_name: postgres-analytics
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: analytics
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - airflow_default

networks:
  airflow_default:
    external: true
