dbt_project:
  outputs:
    dev:
      dbname: analytics
      host: postgres-analytics
      pass: admin123
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: admin
  target: dev
