services:
  mlflow:
    build: .
    container_name: mlflow
    ports:
      - "8081:8080"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      MLFLOW_TRACKING_URI: http://mlflow:8080
    command: >
      mlflow server
        --host 0.0.0.0
        --port 8080
        --disable-security-middleware
        --default-artifact-root s3://mlflow/
        --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-analytics:5432/mlflow
    networks:
      - airflow_default

networks:
  airflow_default:
    external: true