services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.5.1
    container_name: mlflow
    ports:
      - "8081:8080"
    environment:
      # URL de conexión a tu base de datos Postgres
      MLFLOW_TRACKING_URI: http://mlflow:8080
    command: >
      mlflow server
      --host 0.0.0.0
      --port 8080
      --disable-security-middleware
    networks:
      - airflow_default

networks:
  airflow_default:
    external: true